#!/bin/bash
set -e

RATE=44100
CXX=clang++
CXX_FLAGS="-std=c++11 -O3"
if [ -n "$USE_LIBCPP" ]; then 
    CXX_FLAGS+=" -stdlib=libc++"
fi

$CXX $CXX_FLAGS -DRATE=$RATE -DHACK="$1" -DOSCPKT_OSTREAM_OUTPUT -O3 -Wall -Wextra tinyspec.cpp -o "${1%%.*}" -ljack -lfftw3 -lm -lpthread
"${1%%.*}"
