void set_num_channels(size_t in, size_t out);
double now_secs();
double now();
void set_now(double t);
double sample_rate();
WaveBuf get_input_back(double t, size_t n);
WaveBuf get_input_at(double t, size_t n);
void set_max_backbuffer_size(size_t n);
size_t max_backbuffer_size();
void set_latency(size_t n);
size_t latency();
